<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="FundRising" duration-ms="38596" started-at="2019-05-26T03:47:09Z" finished-at="2019-05-26T03:47:47Z">
    <groups>
    </groups>
    <test name="FundRisingapplication test" duration-ms="38596" started-at="2019-05-26T03:47:09Z" finished-at="2019-05-26T03:47:47Z">
      <class name="com.Wonderwe.TestCases.TC_002_AnimalsPage">
        <test-method status="FAIL" signature="Animalsss()[pri:2, instance:com.Wonderwe.TestCases.TC_002_AnimalsPage@402a079c]" name="Animalsss" duration-ms="27992" started-at="2019-05-26T09:17:19Z" finished-at="2019-05-26T09:17:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Page Navigation Error]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Page Navigation Error
	at org.junit.Assert.fail(Assert.java:88)
	at com.Wonderwe.TestCases.TC_002_AnimalsPage.Animalsss(TC_002_AnimalsPage.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Animalsss -->
      </class> <!-- com.Wonderwe.TestCases.TC_002_AnimalsPage -->
      <class name="com.Wonderwe.TestCases.TC_001_HomePage">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.Wonderwe.TestCases.TC_001_HomePage@6500df86]" name="SetUp" is-config="true" duration-ms="32752" started-at="2019-05-26T09:16:36Z" finished-at="2019-05-26T09:17:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="Title()[pri:1, instance:com.Wonderwe.TestCases.TC_001_HomePage@6500df86]" name="Title" duration-ms="10253" started-at="2019-05-26T09:17:09Z" finished-at="2019-05-26T09:17:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Title -->
      </class> <!-- com.Wonderwe.TestCases.TC_001_HomePage -->
    </test> <!-- FundRisingapplication test -->
  </suite> <!-- FundRising -->
</testng-results>
